import { Transaction } from '@prisma/client';
import { differenceInDays, format } from 'date-fns';

export interface Position {
  symbol: string;
  assetType: 'STOCK' | 'CALL' | 'PUT';
  quantity: number;
  averageCost: number; // For options, negative means premium received (short)
  strike?: number | null;
  expiration?: Date | null;
  multiplier: number;
  realizedPnL: number;
}

export interface PortfolioSummary {
  positions: Position[];
  totalRealizedPnL: number;
  historicalMaxCapitalDeployed: number;
  currentMarginLocked: number;
  firstTradeDate: Date | null;
  symbolMaxCapitalDeployed: Record<string, number>;
  symbolFirstTradeDate: Record<string, Date>;
  symbolLastTradeDate: Record<string, Date>;
  symbolRealizedPnL: Record<string, number>;
}

// Helper to uniquely identify an option contract or stock
const getPositionKey = (t: Transaction) => {
  if (t.assetType === 'STOCK') return `${t.symbol}-STOCK`;
  const exp = t.expiration ? t.expiration.toISOString().split('T')[0] : 'NO_EXP';
  return `${t.symbol}-${t.assetType}-${t.strike}-${exp}`;
};

/**
 * Shared position processing engine.
 * Applies a single transaction to an existing position, returning the realized PnL
 * generated by this transaction (if any).
 *
 * This is the single source of truth for position/PnL calculation logic.
 * Both `analyzePortfolio` and `analyzePerformanceHistory` use this function.
 */
function processTransaction(pos: Position, t: Transaction): number {
  let realizedPnL = 0;

  if (t.assetType === 'STOCK') {
    if (t.quantity > 0) {
      // Buy stock — average cost basis
      const totalCost = (pos.quantity * pos.averageCost) + (t.quantity * t.price) + t.fees;
      pos.quantity += t.quantity;
      pos.averageCost = pos.quantity !== 0 ? totalCost / pos.quantity : 0;
    } else {
      // Sell stock — realize PnL
      const sellQty = Math.abs(t.quantity);
      const pnl = ((t.price - pos.averageCost) * sellQty) - t.fees;
      pos.quantity += t.quantity; // quantity is negative for sell
      pos.realizedPnL += pnl;
      realizedPnL = pnl;
      if (pos.quantity === 0) pos.averageCost = 0;
    }
  } else {
    // Options (CALL/PUT)
    if (Math.sign(pos.quantity) === Math.sign(t.quantity) || pos.quantity === 0) {
      // Opening or adding to position
      const tradeCost = (t.price * t.multiplier * t.quantity) + t.fees * Math.sign(t.quantity);
      const totalCost = (pos.quantity * pos.averageCost) + tradeCost;
      pos.quantity += t.quantity;
      pos.averageCost = pos.quantity !== 0 ? totalCost / pos.quantity : 0;
    } else {
      // Closing position
      const closeQty = Math.abs(t.quantity);
      const absQty = Math.abs(pos.quantity);

      // Guard against division by zero
      if (absQty === 0) {
        pos.quantity += t.quantity;
        return 0;
      }

      // Cost basis of the closed portion
      const costBasisOfClosed = pos.averageCost * closeQty * Math.sign(pos.quantity);
      // Proceeds/Cost of closing trade
      const closingTradeValue = t.price * t.multiplier * t.quantity;

      // PnL: if we were short (- qty), closing is buying (+ qty).
      // PnL = Initial Premium Received (which is negative costBasis) - Premium Paid to close - fees
      // Mathematically: -(costBasisOfClosed) - closingTradeValue - t.fees
      const pnl = -(costBasisOfClosed) - closingTradeValue - t.fees;

      pos.quantity += t.quantity;
      pos.realizedPnL += pnl;
      realizedPnL = pnl;
      if (pos.quantity === 0) pos.averageCost = 0;
    }
  }

  return realizedPnL;
}

/**
 * Calculate capital deployed across all current positions.
 */
function calculateCapitalDeployed(positions: Map<string, Position>): {
  totalCapital: number;
  totalMargin: number;
  symbolCapital: Record<string, number>;
} {
  let totalCapital = 0;
  let totalMargin = 0;
  const symbolCapital: Record<string, number> = {};

  for (const [, p] of positions) {
    if (p.quantity === 0) continue;

    let pCapital = 0;
    if (p.assetType === 'STOCK' && p.quantity > 0) {
      pCapital = p.quantity * p.averageCost;
    } else if (p.assetType === 'PUT' && p.quantity < 0) {
      // Short put margin = Strike * 100 * contracts
      pCapital = (p.strike || 0) * p.multiplier * Math.abs(p.quantity);
      totalMargin += pCapital;
    }
    totalCapital += pCapital;
    symbolCapital[p.symbol] = (symbolCapital[p.symbol] || 0) + pCapital;
  }

  return { totalCapital, totalMargin, symbolCapital };
}

/**
 * Create a fresh default position from a transaction.
 */
function createDefaultPosition(t: Transaction): Position {
  return {
    symbol: t.symbol,
    assetType: t.assetType as 'STOCK' | 'CALL' | 'PUT',
    quantity: 0,
    averageCost: 0,
    strike: t.strike,
    expiration: t.expiration,
    multiplier: t.multiplier,
    realizedPnL: 0,
  };
}

export function analyzePortfolio(transactions: Transaction[]): PortfolioSummary {
  // Ensure transactions are chronologically sorted
  const sorted = [...transactions].sort((a, b) => a.tradeDate.getTime() - b.tradeDate.getTime());

  const positions = new Map<string, Position>();
  let totalRealizedPnL = 0;
  let maxCapitalDeployed = 0;

  const symbolMaxCapitalDeployed: Record<string, number> = {};
  const symbolFirstTradeDate: Record<string, Date> = {};
  const symbolLastTradeDate: Record<string, Date> = {};
  const symbolRealizedPnL: Record<string, number> = {};

  for (const t of sorted) {
    if (!symbolFirstTradeDate[t.symbol]) {
      symbolFirstTradeDate[t.symbol] = t.tradeDate;
    }
    symbolLastTradeDate[t.symbol] = t.tradeDate;

    const key = getPositionKey(t);
    const pos = positions.get(key) || createDefaultPosition(t);

    const pnl = processTransaction(pos, t);
    totalRealizedPnL += pnl;
    symbolRealizedPnL[t.symbol] = (symbolRealizedPnL[t.symbol] || 0) + pnl;

    positions.set(key, pos);

    // Calculate simultaneous capital deployed at this moment
    const { totalCapital, symbolCapital } = calculateCapitalDeployed(positions);

    if (totalCapital > maxCapitalDeployed) {
      maxCapitalDeployed = totalCapital;
    }

    for (const sym of Object.keys(symbolCapital)) {
      if (symbolCapital[sym] > (symbolMaxCapitalDeployed[sym] || 0)) {
        symbolMaxCapitalDeployed[sym] = symbolCapital[sym];
      }
    }
  }

  // Current Margin calculation (only active positions)
  let currentMarginLocked = 0;
  const activePositions: Position[] = [];
  for (const [, p] of positions) {
    if (p.quantity !== 0) {
      activePositions.push(p);
      if (p.assetType === 'PUT' && p.quantity < 0) {
        currentMarginLocked += (p.strike || 0) * p.multiplier * Math.abs(p.quantity);
      }
    }
  }

  const firstTradeDate = sorted.length > 0 ? sorted[0].tradeDate : null;

  return {
    positions: activePositions,
    totalRealizedPnL,
    historicalMaxCapitalDeployed: maxCapitalDeployed,
    currentMarginLocked,
    firstTradeDate,
    symbolMaxCapitalDeployed,
    symbolFirstTradeDate,
    symbolLastTradeDate,
    symbolRealizedPnL,
  };
}

export function calculateAnnualizedROIC(roic: number, firstTradeDate: Date | null, endDate: Date = new Date()): number {
  if (!firstTradeDate) return 0;
  const days = differenceInDays(endDate, firstTradeDate);
  if (days <= 0) return roic * 365; // prevent infinity
  return roic * (365 / days);
}

export function formatUTCDate(date: Date | string, formatStr: string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  const localDate = new Date(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate());
  return format(localDate, formatStr);
}

export interface DailyPerformance {
  date: string; // 'yyyy-MM-dd'
  timestamp: number;
  dailyRealizedPnL: number;
  cumulativeRealizedPnL: number;
  maxCapitalDeployed: number;
  cumulativeROIC: number;
}

export function analyzePerformanceHistory(transactions: Transaction[]): DailyPerformance[] {
  if (transactions.length === 0) return [];

  const sorted = [...transactions].sort((a, b) => a.tradeDate.getTime() - b.tradeDate.getTime());
  const history: DailyPerformance[] = [];

  const positions = new Map<string, Position>();
  let totalRealizedPnL = 0;
  let maxCapitalDeployed = 0;

  // Group transactions by UTC date string 'yyyy-MM-dd'
  const txByDate = new Map<string, Transaction[]>();
  for (const t of sorted) {
    const dStr = formatUTCDate(t.tradeDate, 'yyyy-MM-dd');
    if (!txByDate.has(dStr)) txByDate.set(dStr, []);
    txByDate.get(dStr)!.push(t);
  }

  // Generate continuous daily history from first trade to today
  const d = new Date(sorted[0].tradeDate);
  d.setUTCHours(0, 0, 0, 0);
  const end = new Date();
  end.setUTCHours(0, 0, 0, 0);

  while (d <= end) {
    const dStr = format(new Date(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()), 'yyyy-MM-dd');
    let dailyRealizedPnL = 0;

    if (txByDate.has(dStr)) {
      const dailyTxs = txByDate.get(dStr)!;
      for (const t of dailyTxs) {
        const key = getPositionKey(t);
        const pos = positions.get(key) || createDefaultPosition(t);

        const pnl = processTransaction(pos, t);
        totalRealizedPnL += pnl;
        dailyRealizedPnL += pnl;

        positions.set(key, pos);

        const { totalCapital } = calculateCapitalDeployed(positions);
        if (totalCapital > maxCapitalDeployed) {
          maxCapitalDeployed = totalCapital;
        }
      }
    }

    const cumulativeROIC = maxCapitalDeployed > 0 ? (totalRealizedPnL / maxCapitalDeployed) : 0;

    history.push({
      date: dStr,
      timestamp: d.getTime(),
      dailyRealizedPnL,
      cumulativeRealizedPnL: totalRealizedPnL,
      maxCapitalDeployed,
      cumulativeROIC,
    });

    // Increment UTC day safely
    d.setUTCDate(d.getUTCDate() + 1);
  }

  return history;
}
